// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.2
// source: 01.simple/proto/rpc/download.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DownloadClient is the client API for Download service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DownloadClient interface {
	Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (Download_DownloadClient, error)
}

type downloadClient struct {
	cc grpc.ClientConnInterface
}

func NewDownloadClient(cc grpc.ClientConnInterface) DownloadClient {
	return &downloadClient{cc}
}

func (c *downloadClient) Download(ctx context.Context, in *DownloadReq, opts ...grpc.CallOption) (Download_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &Download_ServiceDesc.Streams[0], "/rpc.Download/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &downloadDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Download_DownloadClient interface {
	Recv() (*DownloadRes, error)
	grpc.ClientStream
}

type downloadDownloadClient struct {
	grpc.ClientStream
}

func (x *downloadDownloadClient) Recv() (*DownloadRes, error) {
	m := new(DownloadRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DownloadServer is the server API for Download service.
// All implementations must embed UnimplementedDownloadServer
// for forward compatibility
type DownloadServer interface {
	Download(*DownloadReq, Download_DownloadServer) error
	mustEmbedUnimplementedDownloadServer()
}

// UnimplementedDownloadServer must be embedded to have forward compatible implementations.
type UnimplementedDownloadServer struct {
}

func (UnimplementedDownloadServer) Download(*DownloadReq, Download_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedDownloadServer) mustEmbedUnimplementedDownloadServer() {}

// UnsafeDownloadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DownloadServer will
// result in compilation errors.
type UnsafeDownloadServer interface {
	mustEmbedUnimplementedDownloadServer()
}

func RegisterDownloadServer(s grpc.ServiceRegistrar, srv DownloadServer) {
	s.RegisterService(&Download_ServiceDesc, srv)
}

func _Download_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DownloadServer).Download(m, &downloadDownloadServer{stream})
}

type Download_DownloadServer interface {
	Send(*DownloadRes) error
	grpc.ServerStream
}

type downloadDownloadServer struct {
	grpc.ServerStream
}

func (x *downloadDownloadServer) Send(m *DownloadRes) error {
	return x.ServerStream.SendMsg(m)
}

// Download_ServiceDesc is the grpc.ServiceDesc for Download service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Download_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Download",
	HandlerType: (*DownloadServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Download",
			Handler:       _Download_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "01.simple/proto/rpc/download.proto",
}
