FROM golang:1.22.4 AS builder

LABEL maintainer="zorro" \
      version="1.0.0"

WORKDIR /build

ENV GOPROXY="https://goproxy.cn,https://gocenter.io,https://goproxy.io,direct" \
    GO111MODULE=on \
    GOSUMDB=off \
    GOARCH=amd64 \
    GOOS=linux

COPY . .

RUN go mod tidy

RUN go build -o SERVER ./07.load_balance/server


FROM frolvlad/alpine-glibc AS final

WORKDIR /app

COPY --from=builder /build/SERVER /app/

ENTRYPOINT ./SERVER
