FROM golang:1.22.2 AS builder

LABEL maintainer="zorro" \
      version="1.0.0"

WORKDIR /build

ENV GOPROXY="https://goproxy.cn,https://gocenter.io,https://goproxy.io,direct" \
    GO111MODULE=on \
    GOSUMDB=off \
    GOARCH=amd64 \
    GOOS=linux

COPY . .

RUN go mod tidy

RUN go build -o SERVER --network=host ./cmd/api


FROM frolvlad/alpine-glibc AS final

WORKDIR /app

COPY --from=builder /build/SERVER /app/

#注意这里拷贝文件夹的方式
COPY --from=builder /build/settings /app/conf/

EXPOSE 8002

#ENTRYPOINT ["./SERVER", "start","-c"]
#CMD ["./conf/local.json"]
ENTRYPOINT ./SERVER start -c ./conf/gzl2.json
